#!/bin/bash

# 阿里云部署验证脚本

echo "========================================="
echo "Z-Pulse 阿里云部署验证"
echo "========================================="

echo ""
echo "请手动SSH登录服务器执行以下命令："
echo ""
echo "1. 查看服务状态："
echo "   cd /root/z-pulse && docker-compose ps"
echo ""
echo "2. 查看API日志："
echo "   docker logs zpulse-api --tail 50"
echo ""
echo "3. 查看前端日志："
echo "   docker logs zpulse-web --tail 50"
echo ""
echo "4. 测试API："
echo "   curl http://localhost:8000/api/werss/qrcode"
echo ""
echo "5. 检查磁盘空间："
echo "   df -h"
echo ""
echo "6. 清理Docker空间（如果需要）："
echo "   docker system prune -a"
echo ""
echo "========================================="
echo "验证URL"
echo "========================================="
echo "主应用: http://47.97.115.235:8899"
echo "二维码页面: http://47.97.115.235:8899/we-rss-qrcode-direct"
echo "管理后台: http://47.97.115.235:8899/admin"
echo ""
echo "========================================="
